# Generated by Django 2.2.12 on 2020-05-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads/imgs/'),
        ),
    ]
