# Generated by Django 3.0.5 on 2020-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200515_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
