# Generated by Django 3.0.5 on 2020-05-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_advertisment_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisment',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
